version: '3.8'

services:
  sftp:
    image: atmoz/sftp:latest
    ports:
      - "2222:22"
    volumes:
      - sftp-data:/home/foo/upload
    environment:
      SFTP_USERS: "foo:pass:::upload"
    command: /bin/sh -c "mkdir -p /home/foo/upload && chmod 777 /home/foo/upload && /usr/sbin/sshd -D"

volumes:
  sftp-data: